counting scanned lines in packing menu
akretion/justin_beeper pull request #47
Opened 2018-02-01 08:42 UTC by waf31

Request from Oliverstore

2018-02-05 08:58 UTC, sylvainmerlin commented
@hparfr can you review it ?

2018-02-05 14:47 UTC, hparfr requested changes
Welcome on this project and thanks for this first PR.

You don't need to create and manage a new variable. You can simply query the lengh of the array directly in the view.

2018-02-05 14:47 UTC, hparfr commented on justin/src/colisage/colisage.html
> +        Packing, items scanned {{productCount}}
`{{ model.products.length }}`

2018-02-05 14:47 UTC, hparfr commented on justin/src/colisage/colisage.page.ts
> +  productCount: number = 0;
not needed

2018-02-05 14:47 UTC, hparfr commented on justin/src/colisage/colisage.page.ts
> +    this.productCount ++;
not needed

2018-02-05 14:47 UTC, hparfr commented on justin/src/colisage/colisage.page.ts
> +    this.productCount = 0;
not needed

2018-02-05 16:53 UTC, sylvainmerlin commented
Thanks !

2018-02-06 08:43 UTC, waf31 commented
Hi @hparfr, i have followed your tip and rollback my changes, instead of this i have put your idea of displaying model.products.length

2018-02-06 08:51 UTC, hparfr approved these changes

2018-02-06 08:51 UTC, merged